name: "build multi platform apps"

on:
  push:
    branches:
      - master

jobs:
  build_linux:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "15"
          distribution: "adopt"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Build Android App
        run: flutter build apk --split-per-abi
      - name: Build Web App with auto renderer
        run: |
          flutter build linux
          cd build/linux
          zip -r linux.zip .
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/app/outputs/apk/release/*.apk,build/linux/linux.zip"
  build_windows:
    name: Build Apps
    runs-on: windows-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "15"
          distribution: "adopt"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Build windows
        run: |
          flutter build windows
          cd build/windows
          zip -r windows.zip .

      - name: Build Web App with auto renderer
        run: |
          flutter build web --web-renderer auto
          cd build/web
          zip -r web-app-auto.zip .
      - name: Build Web App with html renderer
        run: |
          flutter build web --web-renderer html
          cd build/web
          zip -r web-app-html.zip .
      - name: Build Web App with canvaskit renderer
        run: |
          flutter build web --web-renderer canvaskit
          cd build/web
          zip -r web-app-canvaskit.zip .
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/windows/windows.zip,build/web/web-app-auto.zip,build/web/web-app-html.zip,build/web/web-app-canvaskit.zip"
  build_macos:
    name: Build Apps
    runs-on: macos-11
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "15"
          distribution: "adopt"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Build Web App with auto renderer
        run: |
          flutter build macos
          cd build/macos
          zip -r macos.zip .
      - name: Release Apps
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.APP_VERSION }}
          name: ${{ env.APP_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "build/ios/iphoneos/app.ipa,build/macos/macos.zip"
